# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos_generated.webcontroller_pb2 as webcontroller__pb2


class AgentStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MoveInformation = channel.unary_unary(
                '/Agent/MoveInformation',
                request_serializer=webcontroller__pb2.MoveInformationRequest.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationReply.FromString,
                )
        self.MoveInformationDeliveryLeft = channel.unary_unary(
                '/Agent/MoveInformationDeliveryLeft',
                request_serializer=webcontroller__pb2.MoveInformationSendLeft.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryRight = channel.unary_unary(
                '/Agent/MoveInformationDeliveryRight',
                request_serializer=webcontroller__pb2.MoveInformationSendRight.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryCenter = channel.unary_unary(
                '/Agent/MoveInformationDeliveryCenter',
                request_serializer=webcontroller__pb2.MoveInformationSendCenter.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryForward = channel.unary_unary(
                '/Agent/MoveInformationDeliveryForward',
                request_serializer=webcontroller__pb2.MoveInformationSendForward.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryBackward = channel.unary_unary(
                '/Agent/MoveInformationDeliveryBackward',
                request_serializer=webcontroller__pb2.MoveInformationSendBackward.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryChangeLeft = channel.unary_unary(
                '/Agent/MoveInformationDeliveryChangeLeft',
                request_serializer=webcontroller__pb2.MoveInformationRequest.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryChangeRight = channel.unary_unary(
                '/Agent/MoveInformationDeliveryChangeRight',
                request_serializer=webcontroller__pb2.MoveInformationRequest.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryChangeCenter = channel.unary_unary(
                '/Agent/MoveInformationDeliveryChangeCenter',
                request_serializer=webcontroller__pb2.MoveInformationRequest.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryChangeForward = channel.unary_unary(
                '/Agent/MoveInformationDeliveryChangeForward',
                request_serializer=webcontroller__pb2.MoveInformationRequest.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryChangeBackward = channel.unary_unary(
                '/Agent/MoveInformationDeliveryChangeBackward',
                request_serializer=webcontroller__pb2.MoveInformationRequest.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationDeliveryStop = channel.unary_unary(
                '/Agent/MoveInformationDeliveryStop',
                request_serializer=webcontroller__pb2.MoveInformationSendStop.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationSendReply.FromString,
                )
        self.MoveInformationGetLastSended = channel.unary_unary(
                '/Agent/MoveInformationGetLastSended',
                request_serializer=webcontroller__pb2.MoveInformationRequest.SerializeToString,
                response_deserializer=webcontroller__pb2.MoveInformationReplyWithStatus.FromString,
                )


class AgentServicer(object):
    """The greeting service definition.
    """

    def MoveInformation(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryLeft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryRight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryCenter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryBackward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryChangeLeft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryChangeRight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryChangeCenter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryChangeForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryChangeBackward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationDeliveryStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInformationGetLastSended(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MoveInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformation,
                    request_deserializer=webcontroller__pb2.MoveInformationRequest.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationReply.SerializeToString,
            ),
            'MoveInformationDeliveryLeft': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryLeft,
                    request_deserializer=webcontroller__pb2.MoveInformationSendLeft.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryRight': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryRight,
                    request_deserializer=webcontroller__pb2.MoveInformationSendRight.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryCenter': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryCenter,
                    request_deserializer=webcontroller__pb2.MoveInformationSendCenter.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryForward': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryForward,
                    request_deserializer=webcontroller__pb2.MoveInformationSendForward.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryBackward': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryBackward,
                    request_deserializer=webcontroller__pb2.MoveInformationSendBackward.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryChangeLeft': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryChangeLeft,
                    request_deserializer=webcontroller__pb2.MoveInformationRequest.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryChangeRight': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryChangeRight,
                    request_deserializer=webcontroller__pb2.MoveInformationRequest.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryChangeCenter': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryChangeCenter,
                    request_deserializer=webcontroller__pb2.MoveInformationRequest.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryChangeForward': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryChangeForward,
                    request_deserializer=webcontroller__pb2.MoveInformationRequest.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryChangeBackward': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryChangeBackward,
                    request_deserializer=webcontroller__pb2.MoveInformationRequest.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationDeliveryStop': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationDeliveryStop,
                    request_deserializer=webcontroller__pb2.MoveInformationSendStop.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationSendReply.SerializeToString,
            ),
            'MoveInformationGetLastSended': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInformationGetLastSended,
                    request_deserializer=webcontroller__pb2.MoveInformationRequest.FromString,
                    response_serializer=webcontroller__pb2.MoveInformationReplyWithStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """The greeting service definition.
    """

    @staticmethod
    def MoveInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformation',
            webcontroller__pb2.MoveInformationRequest.SerializeToString,
            webcontroller__pb2.MoveInformationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryLeft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryLeft',
            webcontroller__pb2.MoveInformationSendLeft.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryRight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryRight',
            webcontroller__pb2.MoveInformationSendRight.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryCenter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryCenter',
            webcontroller__pb2.MoveInformationSendCenter.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryForward',
            webcontroller__pb2.MoveInformationSendForward.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryBackward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryBackward',
            webcontroller__pb2.MoveInformationSendBackward.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryChangeLeft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryChangeLeft',
            webcontroller__pb2.MoveInformationRequest.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryChangeRight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryChangeRight',
            webcontroller__pb2.MoveInformationRequest.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryChangeCenter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryChangeCenter',
            webcontroller__pb2.MoveInformationRequest.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryChangeForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryChangeForward',
            webcontroller__pb2.MoveInformationRequest.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryChangeBackward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryChangeBackward',
            webcontroller__pb2.MoveInformationRequest.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationDeliveryStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationDeliveryStop',
            webcontroller__pb2.MoveInformationSendStop.SerializeToString,
            webcontroller__pb2.MoveInformationSendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveInformationGetLastSended(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Agent/MoveInformationGetLastSended',
            webcontroller__pb2.MoveInformationRequest.SerializeToString,
            webcontroller__pb2.MoveInformationReplyWithStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
